meta_product_name: "Geeft"

meta_title: "Geeft – Trouver le bon cadeau"

meta_description: "Trouvez le cadeau parfait grâce à Geeft, le réseau social de la wishlist."

meta_image: "geeft-cover.png" # should exist in `app/assets/images/`
